import ProjectDescription

let workspace = Workspace(
    name: "MyWorkspace",
    projects: ["."],
    additionalFiles: ["README.md"],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)

